import NavigateNextIcon from '@mui/icons-material/NavigateNext';
import { Button } from '@mui/material';
import { Link } from "react-router-dom";
import StaticSearchBar from '../components/StaticSearchBar';
import PrincipleAnimation from '../components/PrincipleAnimation';
export default function(){
    return (
    <main className="grid grid-cols-2 gap-x-16 max-w-screen-lg mx-auto text-gray-500">
        <section className="mt-48 mb-96">
            <h1 className="text-7xl font-black text-blue-500">AUTOMATIC PIANO KIT</h1>
            <h2 className="text-xl mt-8">Hardware and software setup to automate your piano</h2>
            <div className='mt-6'>
                <Link to="/app">
                    <Button variant="text" size='large'>Test the product <NavigateNextIcon/></Button>
                </Link> 
            </div>
        </section>

        <div></div>
        
        <section className='mb-96'>
            <h1 className="text-4xl font-black text-blue-500">Project goals</h1>
            <h2 className='text-xl mt-8'> 
                Our goal is to develop an affordable prototype for a piano player 
                while providing a software platform for future developers.
            </h2>
            <h2 className='text-xl mt-4'> 
                The estimated cost for the device is about <span className='text-blue-500'>700$</span>
            </h2>
        </section>
         
        <div><StaticSearchBar></StaticSearchBar></div>

        <section>
            <h1 className="text-2xl font-black text-blue-500">Working principle overview</h1>
            <h2 className='text-xl mt-8'> 
                The devices simulates a player's touch by applying force
                on the back side of the keys using <span className='text-blue-500'>solenoids</span>.
            </h2>
            <h2 className='text-xl mt-4'> 
                A comlpex combination of electrical components and software 
                controls the timing and pitch of the notes to be played.
            </h2>
            <div className='mt-6'>
                <Link to="https://www.youtube.com/shorts/YnBFYrcOAl4">
                    <Button variant="text" size='large'>See in action<NavigateNextIcon/></Button>
                </Link> 
            </div>
        </section>
        <div></div>
        <div><PrincipleAnimation/></div>
        {/* <section>
            <h1 className="text-4xl font-black text-blue-500">Solenoids</h1>
            <h2 className='text-xl mt-8'>The driving force of the device are solenoids. Soleoids have central metal rods which are activated and released depending on the magnetic field which is generated by a coil inside the solenoid</h2>
        </section> */}
    </main>)
}